"""Resin: reactive probabilistic logic programming with Reactive Circuits.

A Resin program declares sources (incoming signals), rules and targets.
`Resin.compile` turns it into a reactive circuit that recomputes only what
changed when sources are written.

Example:

    from resin import Resin

    resin = Resin.compile('''
        rain <- source("/weather/rain", Probability).
        wet if rain.
        wet -> target("/wet").
    ''')
    resin.make_writer("/weather/rain").write([0.3])
    rc = resin.get_reactive_circuit()
    print(rc.update())  # {'/wet': array([0.3])}

Main classes: `Resin` (compile programs, create writers), `ReactiveCircuit`
(update targets, adapt to source frequencies) and one writer class per
source type.
"""

# Generated by scripts/generate_stub.py -- do not edit by hand.
from typing import TypedDict

import numpy as np
import numpy.typing as npt

class GradientResult(TypedDict):
    """One target of `ReactiveCircuit.gradient_update()`."""

    probability: float
    gradients: dict[str, float]

class Resin:
    """A compiled Resin program: its sources, reactive circuit and writers.

    Create it with `Resin.compile(model)`, feed source values through writers
    from `make_writer`, and read target values from `get_reactive_circuit()`.
    """

    @staticmethod
    def compile(model: str, value_size: int = 1, verbose: bool = False, semiring: str | None = None, update_threshold: float = 0.001, max_models: int | None = None) -> Resin:
        """Compiles a Resin program into a runtime instance. Every declared target
        is solved with Clingo and added to one shared reactive circuit.

        - `model`: the Resin program text.
        - `value_size`: number of values (probabilities) per source, e.g.
          particles or grid cells evaluated in parallel. `ProbGradient` only
          supports `1`.
        - `verbose`: print the generated ASP programs and model counts.
        - `semiring` (case-insensitive): `"LogProb"` (default), `"MaxProduct"`,
          `"Fuzzy"`, `"Boolean"`, `"ProbGradient"` or `"CriticalExplanation"`.
        - `update_threshold`: minimum change of a leaf value that triggers
          recomputation.
        - `max_models`: raise an error if a target has more stable models.

        Raises `RuntimeError` if the program cannot be compiled.
        """

    def get_reactive_circuit(self) -> ReactiveCircuit:
        """Returns the reactive circuit of this program, which computes the
        targets (`update`, `full_update`) and adapts to source frequencies.
        """

    def read(self, receiver_idx: int, channel: str, invert: bool) -> None:
        """Connects leaf `receiver_idx` to IPC `channel`: values sent there update
        the leaf, as `1 - value` if `invert`. Sources are connected
        automatically; this is only needed for custom wiring.
        Raises `IOError` if the channel cannot be opened.
        """

    def make_writer(self, channel: str) -> ProbabilityWriter | DensityWriter | NumberWriter | BooleanWriter:
        """Returns the writer for the source declared on `channel`, e.g.
        `make_writer("/sensors/speed")`. Its type follows the source type:
        `ProbabilityWriter`, `DensityWriter`, `NumberWriter` or `BooleanWriter`.
        For categorical sources, use `make_categorical_writer`.
        Raises `RuntimeError` if no such source uses `channel`.
        """

    def make_writer_for(self, source_name: str) -> ProbabilityWriter | DensityWriter | NumberWriter | BooleanWriter:
        """Like `make_writer`, but looks the source up by its atom name, e.g.
        `make_writer_for("speed")` or `make_writer_for("distance(hospital)")`.
        Raises `RuntimeError` if no source has that name.
        """

    def make_categorical_writer(self, channel: str) -> CategoricalWriter:
        """Returns the `CategoricalWriter` for the categorical source on `channel`.
        Raises `RuntimeError` if no categorical source uses `channel`.
        """

    def make_timed_writer(self, channel: str, frequency: float) -> SharedVector:
        """Starts a background writer that sends a value to `channel` at
        `frequency` Hz, e.g. to simulate a sensor. Returns the `SharedVector`
        holding the value it sends; change it with `set`.
        Raises `IOError` if the writer cannot be created.
        """

    def stop_timed_writers(self) -> None:
        """Stops all writers started with `make_timed_writer`.
        """

    def get_names(self) -> list[str]:
        """Names of all circuit leaves in index order, e.g. `"alarm"` and its
        complement `"-alarm"`. The position of a name is the leaf index used
        by `ReactiveCircuit.lift_leaf` and `drop_leaf`.
        """

    def get_frequencies(self) -> npt.NDArray[np.float64]:
        """Estimated update frequency (Hz) of every leaf, in index order.
        """

    def get_values(self) -> list[npt.NDArray[np.float64]]:
        """Current value of every leaf as an array of length `value_size`, in
        index order.
        """

    def source_gradients_for(self, gradients: dict[str, float], atom_name: str) -> dict[str, float]:
        """Returns the gradients for a single source looked up by **atom name**.

        `gradients` is the inner `"gradients"` dict from a `gradient_update` /
        `full_gradient_update` result (i.e. `{leaf_name: float}`).
        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """

    def source_gradients(self, gradients: dict[str, float], channel: str) -> dict[str, float]:
        """Returns the gradients for a single source looked up by **channel name**.

        `gradients` is the inner `"gradients"` dict from a `gradient_update` /
        `full_gradient_update` result (i.e. `{leaf_name: float}`).
        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """

    def get_parameter_groups(self) -> dict[str, list[str]]:
        """Returns the learnable parameters found during compilation.

        Each key is `"{predicate}#{clause_index}"`, e.g. `"needs_checkup#0"`,
        and maps to the names of the leaves sharing that clause's `P(...)` value.
        The keys are what `fit_parameters` accepts as `parameters`.
        """

    def fit_parameters(self, gradients: dict[str, float], lr: float, loss: float, parameters: list[str] | None, timestamp: float) -> None:
        """Applies one gradient-descent step to `P(...)` clause parameters.

        Aggregates gradients across all groundings of each parameter group,
        then applies a single shared update so all groundings stay in sync.
        Source atoms and comparison atoms are never modified.

        - `gradients`: the `"gradients"` dict of one target from
          `ReactiveCircuit.gradient_update()`.
        - `lr`: learning rate.
        - `loss`: derivative of the loss with respect to the target
          probability, e.g. `2 * (p - label)` for squared error.
        - `parameters`: keys from `get_parameter_groups()` to update, or `None`
          for all.
        - `timestamp`: time of the update in seconds.

        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """


class ReactiveCircuit:
    """The reactive circuit computing a program's targets. Obtain it with
    `Resin.get_reactive_circuit()`, or build one by hand from leaves and
    sum-products.

    Leaves are addressed by index (see `Resin.get_names()`). Writing to a
    source marks the dependent circuit nodes as outdated; `update()` then
    recomputes only those, `full_update()` everything.
    """

    def __init__(self, value_size: int, update_threshold: float = 0.001, semiring: str | None = None) -> None:
        """The reactive circuit computing a program's targets. Obtain it with
        `Resin.get_reactive_circuit()`, or build one by hand from leaves and
        sum-products.

        Leaves are addressed by index (see `Resin.get_names()`). Writing to a
        source marks the dependent circuit nodes as outdated; `update()` then
        recomputes only those, `full_update()` everything.
        """

    def add_leaf(self, initial_value: npt.ArrayLike, frequency: float, token: str) -> int:
        """Adds a leaf with an initial value (`value_size` probabilities), an
        initial update frequency in Hz and a name. Returns its leaf index.
        """

    def update_leaf(self, leaf_index: int, new_value: npt.ArrayLike, timestamp: float) -> None:
        """Sets the value of leaf `leaf_index` (`value_size` probabilities) at
        `timestamp` (seconds), updates its frequency estimate and marks
        dependent nodes as outdated if the value changed by more than the
        update threshold.
        """

    def add_sum_product(self, sum_product: list[list[int]], target_token: str) -> None:
        """Adds a sum of products of leaf indices to target `target_token`, e.g.
        `[[0, 1], [2]]` for `x0·x1 + x2`. Creates the target if needed.
        """

    def adapt(self, bin_size: float, number_bins: int, dag: bool = True) -> None:
        """Restructures the circuit by leaf update frequency: leaves are grouped
        into `number_bins` bands of `bin_size` Hz, and faster leaves are placed
        higher, so frequent updates recompute only small parts of the circuit.

        `dag=True` (default) shares identical sub-circuits between targets;
        `dag=False` keeps a separate tree per target.
        """

    def update(self) -> dict[str, npt.NDArray[np.float64]]:
        """Recomputes the outdated parts of the circuit. Returns a dict from target
        channel to its value array, containing only the targets that were
        recomputed. Each array has `value_size` values; for
        `CriticalExplanation`, it holds the four blocks `[P | v | tag | w]` of
        `value_size` values each.
        """

    def full_update(self) -> dict[str, npt.NDArray[np.float64]]:
        """Recomputes the whole circuit and returns the values of all targets,
        in the same format as `update()`.
        """

    def gradient_update(self) -> dict[str, GradientResult]:
        """Like `update()`, but returns `{target: {"probability": p, "gradients":
        {leaf_name: dp/dleaf}}}` for the recomputed targets.
        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """

    def full_gradient_update(self) -> dict[str, GradientResult]:
        """Like `full_update()`, in the format of `gradient_update()`.
        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """

    def fit(self, gradients: dict[str, float], lr: float, loss: float, atoms: list[str] | None, timestamp: float) -> None:
        """One gradient-descent step on leaf probabilities:
        `p ← clamp(p - lr * loss * gradient, 0, 1)`.

        `gradients` is the `"gradients"` dict of one target from
        `gradient_update()`, `loss` the derivative of the loss with respect to
        the target probability, `atoms` the leaf names to update (`None` for
        all) and `timestamp` the time of the update in seconds. To learn
        `P(...)` clause parameters of a program, use `Resin.fit_parameters`.
        Raises `RuntimeError` if the semiring is not `ProbGradient`.
        """

    def lift_leaf(self, index: int, dag: bool = True) -> None:
        """Moves leaf `index` one level up, into the parents of the nodes that
        contain it. Use this for a leaf that changes more often than others.
        `dag` as in `adapt`.
        """

    def drop_leaf(self, index: int, dag: bool = True) -> None:
        """Moves leaf `index` one level down, into the children of the nodes that
        contain it. Use this for a leaf that changes less often than others.
        `dag` as in `adapt`.
        """

    def to_dot(self, path: str) -> None:
        """Writes the circuit structure as a Graphviz dot file to `path`.
        """

    def to_svg(self, path: str, keep_dot: bool = False) -> None:
        """Renders the circuit structure to an SVG at `path` (requires Graphviz);
        with `keep_dot`, the dot source is kept as `path + ".dot"`.
        """

    def to_combined_svg(self, path: str) -> None:
        """Renders the circuit together with the formula inside every node to an
        SVG at `path` (requires Graphviz).
        """


class SharedVector:
    """The value of a timed writer (see `Resin.make_timed_writer`), which sends it
    to its channel at a fixed frequency.
    """

    def set(self, value: npt.ArrayLike) -> None:
        """Replaces the value that the timed writer sends from now on.
        """

    def get(self) -> npt.NDArray[np.float64]:
        """Returns the value that the timed writer currently sends.
        """


class ProbabilityWriter:
    """Writer for a `Probability` source: passes probabilities straight through to
    the circuit.
    """

    def write(self, value: npt.ArrayLike, timestamp: float | None = None) -> None:
        """Sends `value`, one probability in `[0, 1]` per value slot (length
        `value_size`). `timestamp` is in seconds; `None` uses the current Unix time.
        """


class DensityWriter:
    """Writer for a `Density` source. A single call dispatches to every comparison
    threshold registered for the source, computing CDF or SF element-wise
    across all value slots (e.g. particle-filter particles).

    Supported distributions and their `params` layout (each inner list is a
    Vector with one value per particle / value-space slot):
    - `"normal"`      → `[means, stds]`
    - `"lognormal"`   → `[log_means, log_stds]`  (natural-log space)
    - `"exponential"` → `[rates]`
    - `"uniform"`     → `[lows, highs]`
    """

    def write(self, distribution: str, params: list[npt.ArrayLike], timestamp: float | None = None) -> None:
        """Sends a distribution, e.g. `write("normal", [[25.0], [5.0]])`.
        `timestamp` is in seconds; `None` uses the current Unix time.
        Raises `ValueError` for an unknown distribution or missing parameters.
        """


class NumberWriter:
    """Writer for a `Number` source. Compares a value vector against every
    registered threshold element-wise: 1.0 where the comparison holds, else 0.0.
    """

    def write(self, value: npt.ArrayLike, timestamp: float | None = None) -> None:
        """Sends `value`, one number per value slot (length `value_size`).
        `timestamp` is in seconds; `None` uses the current Unix time.
        """


class BooleanWriter:
    """Writer for a `Boolean` source. Maps a Python bool to a probability:
    `True` → 1.0, `False` → 0.0.
    """

    def write(self, value: bool, timestamp: float | None = None) -> None:
        """Sends `value` to all value slots.
        `timestamp` is in seconds; `None` uses the current Unix time.
        """


class CategoricalWriter:
    """Writer for a `Categorical` source. Sends a flat probability matrix
    `[col₀, col₁, …]` where each column has `value_size` entries, one per
    value slot.
    """

    def write(self, probabilities: npt.ArrayLike, timestamp: float | None = None) -> None:
        """Sends class probabilities as a flat list of length
        `n_categories() * value_size()`, category by category.
        `timestamp` is in seconds; `None` uses the current Unix time.
        """

    def n_categories(self) -> int:
        """Number of categories of the source.
        """

    def value_size(self) -> int:
        """Number of value slots per category.
        """
