"""Generates `resin.pyi`, the type stub shipped in the Python wheel.

Docstrings come from the built module, type annotations from `SIGNATURES`
below. The script fails if the module's classes, methods or parameter names
differ from `SIGNATURES`, so update the table whenever the Python API changes.

Run after `maturin develop`:  python scripts/generate_stub.py
"""

import inspect
import sys
import textwrap
from pathlib import Path

import resin

ARRAY = "npt.NDArray[np.float64]"
WRITER = "ProbabilityWriter | DensityWriter | NumberWriter | BooleanWriter"

# Class -> method -> (parameters without self, return type).
# A leading "@staticmethod " marks static methods.
SIGNATURES = {
    "Resin": {
        "@staticmethod compile": (
            "model: str, value_size: int = 1, verbose: bool = False, "
            "semiring: str | None = None, update_threshold: float = 0.001, "
            "max_models: int | None = None",
            "Resin",
        ),
        "get_reactive_circuit": ("", "ReactiveCircuit"),
        "read": ("receiver_idx: int, channel: str, invert: bool", "None"),
        "make_writer": ("channel: str", WRITER),
        "make_writer_for": ("source_name: str", WRITER),
        "make_categorical_writer": ("channel: str", "CategoricalWriter"),
        "make_timed_writer": ("channel: str, frequency: float", "SharedVector"),
        "stop_timed_writers": ("", "None"),
        "get_names": ("", "list[str]"),
        "get_frequencies": ("", ARRAY),
        "get_values": ("", f"list[{ARRAY}]"),
        "source_gradients_for": ("gradients: dict[str, float], atom_name: str", "dict[str, float]"),
        "source_gradients": ("gradients: dict[str, float], channel: str", "dict[str, float]"),
        "get_parameter_groups": ("", "dict[str, list[str]]"),
        "fit_parameters": (
            "gradients: dict[str, float], lr: float, loss: float, "
            "parameters: list[str] | None, timestamp: float",
            "None",
        ),
    },
    "ReactiveCircuit": {
        "__init__": (
            "value_size: int, update_threshold: float = 0.001, semiring: str | None = None",
            "None",
        ),
        "add_leaf": ("initial_value: npt.ArrayLike, frequency: float, token: str", "int"),
        "update_leaf": ("leaf_index: int, new_value: npt.ArrayLike, timestamp: float", "None"),
        "add_sum_product": ("sum_product: list[list[int]], target_token: str", "None"),
        "adapt": ("bin_size: float, number_bins: int, dag: bool = True", "None"),
        "update": ("", f"dict[str, {ARRAY}]"),
        "full_update": ("", f"dict[str, {ARRAY}]"),
        "gradient_update": ("", "dict[str, GradientResult]"),
        "full_gradient_update": ("", "dict[str, GradientResult]"),
        "fit": (
            "gradients: dict[str, float], lr: float, loss: float, "
            "atoms: list[str] | None, timestamp: float",
            "None",
        ),
        "lift_leaf": ("index: int, dag: bool = True", "None"),
        "drop_leaf": ("index: int, dag: bool = True", "None"),
        "to_dot": ("path: str", "None"),
        "to_svg": ("path: str, keep_dot: bool = False", "None"),
        "to_combined_svg": ("path: str", "None"),
    },
    "SharedVector": {
        "set": ("value: npt.ArrayLike", "None"),
        "get": ("", ARRAY),
    },
    "ProbabilityWriter": {
        "write": ("value: npt.ArrayLike, timestamp: float | None = None", "None"),
    },
    "DensityWriter": {
        "write": (
            "distribution: str, params: list[npt.ArrayLike], timestamp: float | None = None",
            "None",
        ),
    },
    "NumberWriter": {
        "write": ("value: npt.ArrayLike, timestamp: float | None = None", "None"),
    },
    "BooleanWriter": {
        "write": ("value: bool, timestamp: float | None = None", "None"),
    },
    "CategoricalWriter": {
        "write": ("probabilities: npt.ArrayLike, timestamp: float | None = None", "None"),
        "n_categories": ("", "int"),
        "value_size": ("", "int"),
    },
}

HEADER = '''\
# Generated by scripts/generate_stub.py -- do not edit by hand.
from typing import TypedDict

import numpy as np
import numpy.typing as npt

class GradientResult(TypedDict):
    """One target of `ReactiveCircuit.gradient_update()`."""

    probability: float
    gradients: dict[str, float]
'''


def docstring(obj, indent):
    doc = inspect.cleandoc(obj.__doc__ or "")
    if not doc:
        sys.exit(f"missing docstring: {obj!r}")
    doc = doc.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return textwrap.indent(f'"""{doc}\n"""', indent)


def parameter_names(stub_parameters):
    # Split at top-level commas only, not inside `dict[str, float]`.
    names, depth, current = [], 0, ""
    for char in stub_parameters + ",":
        depth += {"[": 1, "]": -1}.get(char, 0)
        if char == "," and depth == 0:
            if current.strip():
                names.append(current.split(":")[0].strip())
            current = ""
        else:
            current += char
    return names


def check(cls, methods):
    runtime = {
        name
        for name in dir(cls)
        if not name.startswith("_") or (name == "__init__" and "__init__" in methods)
    }
    declared = {key.split()[-1] for key in methods}
    if "__init__" not in declared:
        runtime.discard("__init__")
    if runtime != declared:
        sys.exit(
            f"{cls.__name__}: stub table differs from module "
            f"(missing {sorted(runtime - declared)}, extra {sorted(declared - runtime)})"
        )
    for key, (parameters, _) in methods.items():
        name = key.split()[-1]
        target = cls if name == "__init__" else getattr(cls, name)
        actual = [
            p for p in inspect.signature(target).parameters
            if p not in ("self", "args", "kwargs")
        ]
        if actual != parameter_names(parameters):
            sys.exit(f"{cls.__name__}.{name}: module has {actual}, stub {parameter_names(parameters)}")


def main():
    if not (resin.__doc__ or "").strip():
        sys.exit("missing module docstring")
    lines = [docstring(resin, ""), "", HEADER]
    for class_name, methods in SIGNATURES.items():
        cls = getattr(resin, class_name)
        check(cls, methods)
        lines.append(f"class {class_name}:")
        lines.append(docstring(cls, "    "))
        for key, (parameters, returns) in methods.items():
            static = key.startswith("@staticmethod ")
            name = key.split()[-1]
            parameters = parameters if static else ", ".join(p for p in ["self", parameters] if p)
            doc_source = cls if name == "__init__" else getattr(cls, name)
            lines.append("")
            if static:
                lines.append("    @staticmethod")
            lines.append(f"    def {name}({parameters}) -> {returns}:")
            lines.append(docstring(doc_source, "        "))
        lines.append("\n")

    path = Path(__file__).resolve().parent.parent / "resin.pyi"
    path.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
